# Generated by Django 2.1.5 on 2020-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('searching_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
