# Generated by Django 2.1.5 on 2020-03-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='searching_date',
            field=models.DateTimeField(),
        ),
    ]
