# Generated by Django 2.1.5 on 2020-03-31 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0002_auto_20200327_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='add_date',
            field=models.DateTimeField(),
        ),
    ]
