# Generated by Django 2.1.5 on 2020-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma', '0002_auto_20200420_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='searching_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
